export const COMPONENT = {
  REST_APPLICATION: Symbol.for('RestApplication'),
  LOGGER: Symbol.for('Logger'),
  CONFIG: Symbol.for('Config'),
  DATABASE_CLIENT: Symbol.for('DatabaseClient'),
  USER_SERVICE: Symbol.for('UserService'),
  USER_MODEL: Symbol.for('UserModel'),
  OFFER_SERVICE: Symbol.for('OfferService'),
  OFFER_MODEL: Symbol.for('OfferModel'),
  COMMENT_MODEL: Symbol.for('CommentModel'),
  COMMENT_SERVICE: Symbol.for('CommentService'),
  OFFER_CONTROLLER: Symbol.for('OfferController'),
  USER_CONTROLLER: Symbol.for('UserController'),
  EXCEPTION_FILTER: Symbol.for('ExceptionFilter'),
  AUTH_SERVICE: Symbol.for('AuthService'),
  AUTH_EXCEPTION_FILTER: Symbol.for('AuthExceptionFilter'),
  HTTP_EXCEPTION_FILTER: Symbol.for('HttpExceptionFilter'),
  VALIDATION_EXCEPTION_FILTER: Symbol.for('ValidationExceptionFilter'),
  PATH_TRANSFORMER: Symbol.for('PathTransformer'),
} as const;
